# Codemagic CI/CD Configuration for LineLibrary
# Docs: https://docs.codemagic.io/yaml/yaml-getting-started/

workflows:
  # iOS App Store Build
  ios-release:
    name: iOS App Store Release
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - app_store_credentials
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.linelibrary.app
      vars:
        BUNDLE_ID: "com.linelibrary.app"

    integrations:
      app_store_connect: Codemagic

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Create certificate key file
        script: |
          echo "$CERTIFICATE_PRIVATE_KEY" > $CM_BUILD_DIR/cert_key.pem

      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create \
            --certificate-key=@file:$CM_BUILD_DIR/cert_key.pem
          keychain add-certificates

      - name: Install CocoaPods
        script: |
          cd ios
          pod install --repo-update

      - name: Flutter build iOS
        script: |
          flutter build ios --release --no-codesign

      - name: Build and sign IPA
        script: |
          xcode-project use-profiles
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --scheme Runner \
            --config Release

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log

    publishing:
      app_store_connect:
        # API Key authentication - set these in Environment variables
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        # submit_to_app_store: true  # Uncomment for production release

  # Android Play Store Build
  android-release:
    name: Android Play Store Release
    max_build_duration: 30
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      groups:
        - play_store_credentials # Google Play credentials (set in Codemagic UI)
      vars:
        PACKAGE_NAME: "com.linelibrary.app" # Update with your package name

    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get

      - name: Build Android App Bundle
        script: |
          flutter build appbundle --release \
            --build-name=1.0.0 \
            --build-number=$PROJECT_BUILD_NUMBER

    artifacts:
      - build/app/outputs/bundle/release/*.aab
      - build/app/outputs/mapping/release/mapping.txt

    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal # Options: internal, alpha, beta, production
        submit_as_draft: true
